name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7
      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws  # Créer le répertoire .aws s'il n'existe pas
          echo "[default]" > ~/.aws/config
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          cat ~/.aws/credentials

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "github_token=${{ secrets.GH_OAUTH_TOKEN }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "github_token=${{ secrets.GH_OAUTH_TOKEN }}"